export const MembershipTypeDetails = {
    RESIDENT_LIFE_MEMBER: "RESIDENT LIFE MEMBER",
    OVERSEAS_LIFE_MEMBER: "OVERSEAS LIFE MEMBER",
    ORDINARY_MEMBERS: "ORDINARY MEMBERS",
    PLAYING_MEMBER: "PLAYING MEMBER",
  };